some description

In [28]:
import pandas as pd

df = pd.DataFrame([[1,2,3],[5,6,7]], columns=["A" , "B" , "C"], index=["Sarvin" , "ali"])
df

        A  B  C
Sarvin  1  2  3
ali     5  6  7

In [29]:
pd.DataFrame({ "name" : ["mina" , "ali"],
              "age" : [20,30]})

   name  age
0  mina   20
1   ali   30

In [33]:
pd.read_excel('./1.xlsx')
df = pd.read_csv('./world_population.csv')
df.head(10)
df.tail(10)
df.sample(5)

#df.info(verbose=False)
df.describe()
df.shape
df.columns

df["Country"].describe()

count             234
unique            234
top       Afghanistan
freq                1
Name: Country, dtype: object